version: '3.3'

services:
  db:
    container_name: db
    build: ./docker/postgresql/
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  app:
    container_name: app
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    ports:
      - 3333:3333
    depends_on:
      - db
